### ISSUE TITLE
upgrading webpack-dev-server

### ISSUE THREAD

**Issue by headwinds** [lexey111/preact-typescript-webpack4-boilerplate#4]
I couldn't get `yarn start` to work since it complained about `webpack-cli/bin/config-yargs`

I followed [this thread](https://github.com/webpack/webpack-dev-server/issues/2029) to update webpack-dev-server and since I was updating it, I thought I might as well update typescript, ts-loader, & webpack-cli too 

I'll create a fork for this changes and do a PR if that's cool... 

changes:
```
"devDependencies": {
		"copy-webpack-plugin": "^4.5.2",
		"file-loader": "^1.1.11",
		"fork-ts-checker-webpack-plugin": "^1.3.7",
		"less": "^3.8.0",
		"less-loader": "^4.1.0",
		"less-plugin-clean-css": "^1.5.1",
		"rimraf": "^2.6.2",
		"ts-loader": "6.2.0",
		"typescript": "3.6.4",
		"webpack": "^4.16.3",
		"webpack-cli": "3.3.9",
		"webpack-dev-server": "3.7.1" 
	}
```

**Comment by lexey111** [comment]
yes, thank you, i'd be appreciated.

**Comment by azhanali** [comment]
It works fine in these versions too:-
    "webpack": "^5.4.0",
    "webpack-cli": "^3.3.12",
    "webpack-dev-server": "^3.7.1"
